明解JAVA 14-1まで完了
ddt-hosoya/meikai_java_hosoya pull request #132
Opened 2020-02-26 11:10 UTC by ddt-hosoya

2020-07-27 11:48 UTC, ddt-mentor requested changes

2020-07-27 11:48 UTC, ddt-mentor commented on meikai_java/src/e14/e14_01_Rectangle.java
> +	/**
widthとheightに関しては親クラスで宣言されているので、ここで宣言しなおす必要はありません。(石井)

2020-07-27 11:48 UTC, ddt-mentor commented on meikai_java/src/e14/e14_01_Rectangle.java
> +		return width * height;
親クラスのフィールドを活用したロジックに変えてみてください。(石井)

2020-07-27 11:48 UTC, ddt-mentor commented on meikai_java/src/e14/e14_01_Parallelogram.java
> +	/**
widthとheightに関しては親クラスで宣言されているので、ここで宣言しなおす必要はありません。(石井)

2020-07-27 11:48 UTC, ddt-mentor commented on meikai_java/src/e14/e14_01_Parallelogram.java
> +		// 1段ずつ上から描画します
親クラスのフィールドを活用したロジックに変えてみてください。(石井)

2020-07-27 11:48 UTC, ddt-mentor commented on meikai_java/src/e14/e14_01_Parallelogram.java
> +		// 面積（底辺×高さ）を返却
親クラスのフィールドを活用したロジックに変えてみてください。(石井)

2020-09-02 11:57 UTC, ddt-hosoya commented on meikai_java/src/e14/e14_01_Rectangle.java
> +	/**
親クラスのフィールドがprivateかつgetterを作成していないクラスだったのですが、親クラスを変更せずに参照することは可能でしょうか？（細谷）

2020-09-02 11:57 UTC, ddt-hosoya commented on meikai_java/src/e14/e14_01_Rectangle.java
> +		return width * height;
親クラスのフィールドがprivateかつgetterを作成していないクラスだったのですが、親クラスを変更せずに参照することは可能でしょうか？（細谷）

2020-09-02 12:00 UTC, ddt-hosoya commented on meikai_java/src/e14/e14_01_Parallelogram.java
> +		// 1段ずつ上から描画します
親クラス「e13_01_Shape」ではこれらのフィールドは宣言していませんでした（細谷）

2020-09-02 12:00 UTC, ddt-hosoya commented on meikai_java/src/e14/e14_01_Parallelogram.java
> +		// 面積（底辺×高さ）を返却
親クラス「e13_01_Shape」ではこれらのフィールドは宣言していませんでした（細谷）

2020-09-02 12:06 UTC, ddt-hosoya commented on meikai_java/src/e14/e14_01_Parallelogram.java
> +	/**
親クラス「e13_01_Shape」ではこれらのフィールドは宣言していませんでした（細谷）

2020-09-28 11:47 UTC, merged